config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: %i[show edit update destroy]
  def index
    @flats = Flat.all
    @num = Flat.count
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(params[:id])
    @flat = Flat.new(flat_params)
    @flat.save
    redirect_to flat_path(@flat)
  end

  def show
  end

  def edit
  end

  def update
    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end

  def destroy
    @flat.destroy
    redirect_to flats_path, status: :see_other
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end

  def set_flat
    @flat = Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<div class='px-2 py-3 rounded border shadow m-5'>
  <%= simple_form_for flat do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>
</div>

app/views/flats/edit.html.erb
<h2>Edit <%= @flat.name %>:</h1>
<%= render 'form', flat: @flat %>

app/views/flats/index.html.erb
<div class='container mt-4'>
  <h2>All our flats (<%=@num%>)</h2>
  <div class="row">
    <% @flats.each do |flat|%>
      <div class='col-md-4 mb-4 p-0 rounded border shadow'>
        <div class='card-top p-4 bg-light'>
          <h4><%= flat.name %></h4>
          <p><%= flat.address %></p>
          <div class="d-flex justify-content-left">
            <p>🧑‍🤝‍🧑 <%= flat.number_of_guests %></p>
            <p>💲 <%= flat.price_per_night %></p>
          </div>
        </div>
        <div class='card-bottom w-100 p-4 border'>
          <%= link_to 'More info', flat_path(flat)%>
          <%= link_to 'Edit', edit_flat_path(flat)%>
          <%= link_to 'Remove', flat_path(flat), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}%>
        </div>

      </div>
    <%end%>
  </div>
</div>

app/views/flats/new.html.erb
<h2>Add new flat:</h1>
<%= simple_form_for @flat do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit "Add flat", class: "btn btn-primary" %>
<% end %>

app/views/flats/show.html.erb
  <div class="row m-0">
    <div class='col mx-5'>

      <div class='px-2 py-3 rounded border shadow my-4'>
        <h2> <%=@flat.name%> </h2>
        <h6> <%=@flat.address%> </h6>
      </div>

      <div class='px-2 py-3 rounded border shadow mb-4'>
        <h3>A bit more about this flat...</h3>
        <p> <%=@flat.description%> </p>

      </div>

      <div class='px-2 py-3 rounded border shadow'>
        <h3>Details</h3>
        <div class="d-flex justify-content-start">
          <p>🧑‍🤝‍🧑 <%= @flat.number_of_guests %></p>
          <p>💲 <%= @flat.price_per_night %></p>
        </div>
      </div>

      <div class='px-2 py-3 rounded border shadow'>
        <%= link_to 'Edit', edit_flat_path(@flat)%>
        <%= link_to 'Remove', flat_path(@flat), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}%>
      </div>


    </div>

    <div class='col mt-4'>
      <p>Some booking info here</p>
    </div>

  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/flats">Simple Airbnb</a>
    <a class="navbar-brand btn btn-primary border rounded" href="flats/new">Add Flat</a>
  </nav>

    <%= yield %>
  </body>
</html>